#!/bin/bash
mkdir build
cd build
rm -r TileDB-Java
git clone https://github.com/TileDB-Inc/TileDB-Java.git
cd TileDB-Java
git checkout master
git pull
./gradlew assemble publishToMavenLocal --stacktrace --debug --info
cd ../..
