#!/bin/bash
if [ -d "TileDB-Java" ]; then
  rm -r ./TileDB-Java
fi
git clone https://github.com/TileDB-Inc/TileDB-Java.git
pushd TileDB-Java
git checkout 0.1.7
./gradlew assemble --info
./gradlew publishToMavenLocal --info
popd
