name: TileDB-Spark

on:
  push:
    tags: [ v* ]
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    name: Ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls; pwd;
      - run: unset SYSTEM; ./gradlew checkFormat;
        shell: bash
      - run: unset SYSTEM; ./gradlew assemble;
        shell: bash
      - run: unset SYSTEM; ./gradlew test;
        shell: bash