name: GitHub Actions Demo
on: [push]
jobs:
  UBUNTU:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls; pwd;
      - run: unset SYSTEM; ../.././gradlew checkFormat;
      - run: unset SYSTEM; ../.././gradlew assemble;
      - run: unset SYSTEM; ../.././gradlew test;